### PR TITLE
docs: minor text fixes

### PR DESCRIPTION
**Pull request by HorusGoul**
[skip ci]

### CODE REVIEW

**Comment by HorusGoul** [comment]
@all-contributors please add @HorusGoul maintenance

**Comment by HorusGoul** [comment]
@all-contributors please add @HorusGoul for ideas, code, design, review, infra

**Comment by HorusGoul** [comment]
@all-contributors please add @silas229 , @alexprave and @HorusGoul  for translation

**Comment by HorusGoul** [comment]
@all-contributors please add  @alexprave for translation

**Comment by HorusGoul** [comment]
@all-contributors please add @HorusGoul for translation

**Comment by HorusGoul** [comment]
@all-contributors please add @silas229 for translation

Sorry in case these comments are bothering you 😅

**Comment by HorusGoul** [comment]
@all-contributors please add @alexprave  for translation

Sorry in case these comments are bothering you 😅

**Comment by silas229** [comment]
> @all-contributors please add @silas229 for translation
> 
> Sorry in case these comments are bothering you 😅

Everything's fine 👍

**Pull request closed without merging**
